name: publish-docker
on: push

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
         uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: my_exposed_username
          password: my_exposed_password_123
      
      - name: Build and publish
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: <docker namespace>/<docker repository>:<tag>